apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a1gqicac7-go 
  janus-idp.io/tekton: a1gqicac7-go
  backstage.io/kubernetes-id: a1gqicac7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a1gqicac7-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  